# Air R Formatter configuration file
# Managed in ~/.doom.d/configs/air.toml

[format]
line-width = 72
indent-width = 4
indent-style = "space"
line-ending = "auto"
persistent-line-breaks = true
assignment-style = "arrow"
exclude = []
default-exclude = true
skip = []
table = []
default-table = true
